{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "38260e07",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial state:\n",
      "1 2 3\n",
      "0 4 6\n",
      "7 5 8\n",
      "\n",
      "Target state:\n",
      "1 2 3\n",
      "4 5 6\n",
      "7 8 0\n",
      "\n",
      "Solving...\n",
      "\n",
      "Solution:\n",
      "Step 1: RIGHT\n",
      "Step 2: DOWN\n",
      "Step 3: RIGHT\n"
     ]
    }
   ],
   "source": [
    "class PuzzleNode:\n",
    "    def __init__(self, state, parent=None, move=None, depth=0, cost=0):\n",
    "        self.state = state\n",
    "        self.parent = parent\n",
    "        self.move = move\n",
    "        self.depth = depth\n",
    "        self.cost = cost\n",
    "    \n",
    "    def __lt__(self, other):\n",
    "        return (self.depth + self.cost) < (other.depth + other.cost)\n",
    "\n",
    "def print_puzzle(state):\n",
    "    for row in state:\n",
    "        print(\" \".join(map(str, row)))\n",
    "\n",
    "def find_blank(state):\n",
    "    for row in range(3):\n",
    "        for col in range(3):\n",
    "            if state[row][col] == 0:\n",
    "                return row, col\n",
    "\n",
    "def is_valid(row, col):\n",
    "    return 0 <= row < 3 and 0 <= col < 3\n",
    "\n",
    "def generate_moves(row, col):\n",
    "    moves = []\n",
    "    if is_valid(row-1, col):\n",
    "        moves.append((-1, 0, \"UP\"))\n",
    "    if is_valid(row+1, col):\n",
    "        moves.append((1, 0, \"DOWN\"))\n",
    "    if is_valid(row, col-1):\n",
    "        moves.append((0, -1, \"LEFT\"))\n",
    "    if is_valid(row, col+1):\n",
    "        moves.append((0, 1, \"RIGHT\"))\n",
    "    return moves\n",
    "\n",
    "def apply_move(state, row, col, move):\n",
    "    new_state = [row[:] for row in state]\n",
    "    dr, dc, _ = move\n",
    "    new_state[row][col], new_state[row+dr][col+dc] = new_state[row+dr][col+dc], new_state[row][col]\n",
    "    return new_state\n",
    "\n",
    "def heuristic(state, target):\n",
    "    count = 0\n",
    "    for row in range(3):\n",
    "        for col in range(3):\n",
    "            if state[row][col] != target[row][col]:\n",
    "                count += 1\n",
    "    return count\n",
    "\n",
    "def a_star_search(initial_state, target_state):\n",
    "    open_list = []\n",
    "    closed_set = set()\n",
    "    \n",
    "    initial_node = PuzzleNode(initial_state, cost=heuristic(initial_state, target_state))\n",
    "    heapq.heappush(open_list, initial_node)\n",
    "    \n",
    "    while open_list:\n",
    "        current_node = heapq.heappop(open_list)\n",
    "        closed_set.add(tuple(map(tuple, current_node.state))) \n",
    "        \n",
    "        if current_node.state == target_state:\n",
    "            moves = []\n",
    "            while current_node.parent:\n",
    "                moves.append(current_node.move)\n",
    "                current_node = current_node.parent\n",
    "            return moves[::-1]\n",
    "        \n",
    "        blank_row, blank_col = find_blank(current_node.state)\n",
    "        possible_moves = generate_moves(blank_row, blank_col)\n",
    "        \n",
    "        for dr, dc, move in possible_moves:\n",
    "            new_state = apply_move(current_node.state, blank_row, blank_col, (dr, dc, move))\n",
    "            \n",
    "            if tuple(map(tuple, new_state)) not in closed_set:\n",
    "                new_node = PuzzleNode(new_state, parent=current_node, move=move, depth=current_node.depth+1, cost=heuristic(new_state, target_state))\n",
    "                heapq.heappush(open_list, new_node)\n",
    "    \n",
    "    return None\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    initial_state = [[1, 2, 3], [0, 4, 6], [7, 5, 8]]\n",
    "    target_state = [[1, 2, 3], [4, 5, 6], [7, 8, 0]]\n",
    "    \n",
    "    print(\"Initial state:\")\n",
    "    print_puzzle(initial_state)\n",
    "    \n",
    "    print(\"\\nTarget state:\")\n",
    "    print_puzzle(target_state)\n",
    "    \n",
    "    print(\"\\nSolving...\")\n",
    "    solution = a_star_search(initial_state, target_state)\n",
    "    \n",
    "    if solution is None:\n",
    "        print(\"\\nNo solution found!\")\n",
    "    else:\n",
    "        print(\"\\nSolution:\")\n",
    "        for step, move in enumerate(solution, start=1):\n",
    "            print(f\"Step {step}: {move}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7c0ac964",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
